services:
  bungle.entity.discover:
    class: Bungle\FrameworkBundle\Entity\ArrayEntityDiscovery
    arguments: [[]]

  bungle.entity.meta_resolver:
    class: Bungle\FrameworkBundle\Entity\ArrayEntityMetaResolver
    arguments: [[]]

  bungle.entity.meta_repository:
    class: Bungle\FrameworkBundle\Entity\EntityMetaRepository
    arguments: ["@bungle.entity.registry", "@bungle.entity.meta_resolver"]

  bungle.entity.high_resolver:
    class: Bungle\FrameworkBundle\Entity\ArrayHighResolver
    arguments: [[]]

  bungle.entity.registry:
    class: Bungle\FrameworkBundle\Entity\EntityRegistry
    arguments: ["@bungle.entity.discover", "@bungle.entity.high_resolver"]

  Bungle\FrameworkBundle\Entity\EntityMetaRepository: '@bungle.entity.meta_repository'
  Bungle\FrameworkBundle\Entity\EntityRegistry: '@bungle.entity.registry'

  bungle.framework.state_machine.transition_event_listener:
    public: false
    class: Bungle\FrameworkBundle\StateMachine\EventListener\TransitionEventListener 
    tags:
      - { name: kernel.event_listener, event: workflow.transition }
    arguments: ["@bungle.entity.registry"]

  bungle.framework.state_machine.transition_role_guard_listener:
    public: false
    class: Bungle\FrameworkBundle\StateMachine\EventListener\TransitionRoleGuardListener  
    tags:
      - { name: kernel.event_listener, event: workflow.guard }
    arguments: ["@security.authorization_checker"]

  bungle.workflow.vina:
    public: false
    class: Bungle\FrameworkBundle\StateMachine\Vina
    arguments: ["@workflow.registry", "@security.authorization_checker"]

  Bungle\FrameworkBundle\StateMachine: '@bungle.workflow.vina'

