services:
  bungle.entity_locator:
    class: Bungle\FrameworkBundle\Meta\SimpleEntityLocator
    arguments: [[]]

  bungle.framework.logic_name:
    class: Bungle\FrameworkBundle\Meta\LogicName
    # By default use a empty EntityDiscover, use DoctrineBungleBridgeBundle to override
    arguments: ["@bungle.entity_locator"]

  bungle.framework.high_prefix:
    class: Bungle\FrameworkBundle\Meta\HighPrefix
    # By default use a empty EntityDiscover, use DoctrineBungleBridgeBundle to override
    arguments: ["@bungle.entity_locator"]

  Bungle\FrameworkBundle\Meta\LogicName: '@bungle.framework.logic_name'
  Bungle\FrameworkBundle\Meta\HighPrefix: '@bungle.framework.high_prefix'

  bungle.framework.state_machine.transition_event_listener:
    public: false
    class: Bungle\FrameworkBundle\StateMachine\EventListener\TransitionEventListener 
    tags:
      - { name: kernel.event_listener, event: workflow.transition }
    arguments: ["@bungle.framework.high_prefix"]

  bungle.framework.state_machine.transition_role_guard_listener:
    public: false
    class: Bungle\FrameworkBundle\StateMachine\EventListener\TransitionRoleGuardListener  
    tags:
      - { name: kernel.event_listener, event: workflow.guard }
    arguments: ["@security.authorization_checker"]

  bungle.workflow.vina:
    public: false
    class: Bungle\FrameworkBundle\StateMachine\Vina
    arguments: ["@workflow.registry", "@security.authorization_checker"]

  Bungle\FrameworkBundle\StateMachine: '@bungle.workflow.vina'

